# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: NuGet push
      uses: edumserrano/nuget-push@v1.2.2
      with:
        # The API key for the NuGet server. Used when pushing the NuGet packages and symbols.
        api-key: ${{ secrets.GITHUB_TOKEN }}
        # The directory that will be used to push NuGet packages. It will push all NuGet packages (*.nupkg) and corresponding symbol packages (*.snupkg) present in the directory.
        working-directory: BoletoNetCore/
        # The filepath for the NuGet package to be pushed.
        nuget-package: BoletoNetCore/bin/Release/BoletoNetCore.3.0.0.nupkg
