# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: NuGet Publisher
      # You may pin to the exact commit or the version.
      # uses: Jacup/publish-nuget@0d7b0c6f119fadaf9c3e2bcfcbb3bf3a1c439864
      uses: Jacup/publish-nuget@v2.6.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: BoletoNetCore/
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: teste_publish_
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: https://nuget.pkg.github.com/vitorsobral/index.json
